using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace Mission06_Hill.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new MovieFormContext(
                serviceProvider.GetRequiredService<DbContextOptions<MovieFormContext>>()))
            {
                // Check if database has been seeded
                if (context.Movies.Any())
                {
                    return; // Database has been seeded
                }

                // Seed Categories first
                var categories = new Dictionary<string, int>();
                var categoryList = new[] { "Action/Adventure", "Comedy", "Drama", "Family", "Horror/Suspense", "Miscellaneous", "Television", "VHS" };
                foreach (var catName in categoryList)
                {
                    var category = new Category { CategoryName = catName };
                    context.Categories.Add(category);
                }
                context.SaveChanges();

                // Reload categories with IDs
                foreach (var cat in context.Categories)
                {
                    categories[cat.CategoryName] = cat.CategoryId;
                }

                // Seed Ratings
                var ratings = new Dictionary<string, int>();
                var ratingList = new[] { "G", "PG", "PG-13", "R", "NR", "UR", "TV-G", "TV-PG", "TV-14", "TV-Y7", "R?" };
                foreach (var ratName in ratingList)
                {
                    var rating = new Rating { RatingName = ratName };
                    context.Ratings.Add(rating);
                }
                context.SaveChanges();

                // Reload ratings with IDs
                foreach (var rat in context.Ratings)
                {
                    ratings[rat.RatingName] = rat.RatingId;
                }

                // Seed Directors and Movies from CSV data
                var directors = new Dictionary<string, int>();

                // Helper method to get or create director
                int GetOrCreateDirector(string directorName)
                {
                    if (directors.ContainsKey(directorName))
                    {
                        return directors[directorName];
                    }

                    var director = new Director { DirectorName = directorName };
                    context.Directors.Add(director);
                    context.SaveChanges();
                    directors[directorName] = director.DirectorId;
                    return director.DirectorId;
                }

                // Add all movies from Joel's CSV
                var movies = new List<(string Category, string Title, string Year, string Director, string Rating, bool Edited, string LentTo, string Notes)>
                {
                    ("Miscellaneous", "29", "2003", "Alan Seawright", "NR", false, "", ""),
                    ("Drama", "127 Hours", "2010", "Danny Boyle", "R", true, "", "Plex"),
                    ("Television", "24 (Season 1)", "2001-2002", "Joel Surnow, Robert Cochran", "TV-14", false, "", "Plex"),
                    ("Television", "24 (Season 2)", "2002-2003", "Joel Surnow, Robert Cochran", "TV-14", false, "", "Plex"),
                    ("Television", "24 (Season 3)", "2003-2004", "Joel Surnow, Robert Cochran", "TV-14", false, "", "Plex"),
                    ("Horror/Suspense", "28 Days Later", "2002", "Danny Boyle", "R", true, "", "Plex"),
                    ("Miscellaneous", "29: Day 2", "2004", "Alan Seawright", "NR", false, "", ""),
                    ("Horror/Suspense", "39 Steps", "1935", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Horror/Suspense", "Abbott and Costello Meet Frankenstein", "1948", "Charles Barton", "NR", false, "", "Plex"),
                    ("Horror/Suspense", "Abominable Dr. Phibes, The", "1971", "Robert Fuest", "PG-13", false, "", "Plex"),
                    ("Drama", "About Time", "2013", "Richard Curtis", "R", true, "", "Plex"),
                    ("Comedy", "Ace Ventura: Pet Detective", "1994", "Tom Shadyac", "PG-13", false, "", "?"),
                    ("Television", "Adventures of Brisco County, Jr.: The Complete Series, The", "1993-1994", "Carlton Cuse, Jeffrey Boam", "TV-PG", false, "", "Plex"),
                    ("Family", "Adventures of Ichabod and Mr. Toad, The", "1949", "Clyde Geronimi, Jack Kinney, James Algar", "G", false, "", "Plex"),
                    ("Family", "Aladdin", "1992", "Ron Clements, John Musker", "G", false, "", "Plex"),
                    ("Comedy", "Amélie", "2001", "Jean-Pierre Jeunet", "R", true, "", "Plex"),
                    ("Family", "An American Tail", "1986", "Don Bluth", "G", false, "", "Plex"),
                    ("Family", "An American Tail: Fievel Goes West", "1991", "Phil Nibbelink, Simon Wells", "G", false, "", "Plex"),
                    ("Comedy", "Anchorman: The Legend of Ron Burgundy", "2004", "Adam McKay", "PG-13", true, "", "Plex"),
                    ("Comedy", "Animal Crackers", "1930", "Victor Heerman", "G", false, "", "Blu-ray"),
                    ("Family", "Annie", "1982", "John Huston", "PG", false, "", "Plex"),
                    ("Television", "Arrested Development (Season 1)", "2003-2004", "Mitchell Hurwitz", "TV-PG", false, "", "Plex"),
                    ("Television", "Arrested Development (Season 2)", "2004-2005", "Mitchell Hurwitz", "TV-14", false, "", "Plex"),
                    ("Television", "Arrested Development (Season 3)", "2005-2006", "Mitchell Hurwitz", "TV-14", false, "", "Plex"),
                    ("Television", "Avatar: The Last Airbender (Book 1)", "2005", "Michael Dante DiMartino, Bryan Konietzko", "TV-Y7", false, "", "Plex"),
                    ("Television", "Avatar: The Last Airbender (Book 2)", "2006", "Michael Dante DiMartino, Bryan Konietzko", "TV-Y7", false, "", "Plex"),
                    ("Television", "Avatar: The Last Airbender (Book 3)", "2007-2008", "Michael Dante DiMartino, Bryan Konietzko", "TV-Y7", false, "", "Plex"),
                    ("Action/Adventure", "Avengers, The", "2012", "Joss Whedon", "PG-13", false, "", "Plex"),
                    ("Comedy", "Back to the Future", "1985", "Robert Zemeckis", "PG", false, "", "Plex"),
                    ("Comedy", "Back to the Future Part II", "1989", "Robert Zemeckis", "PG", false, "", "Plex"),
                    ("Comedy", "Back to the Future Part III", "1990", "Robert Zemeckis", "PG", false, "", "Plex"),
                    ("Comedy", "Barefoot in the Park", "1967", "Gene Saks", "G", false, "", "Plex"),
                    ("Miscellaneous", "Barenaked Ladies - Barelaked Nadies", "2002", "Tim Hamilton", "NR", false, "", ""),
                    ("Action/Adventure", "Batman", "1989", "Tim Burton", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Batman & Robin", "1997", "Joel Schumacher", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Batman Begins", "2005", "Christopher Nolan", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Batman Forever", "1995", "Joel Schumacher", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Batman Returns", "1992", "Tim Burton", "PG-13", false, "", "Plex"),
                    ("Family", "Beauty and the Beast", "1991", "Kirk Wise, Gary Trousdale", "G", false, "", "Plex"),
                    ("Comedy", "Beetlejuice", "1988", "Tim Burton", "PG-13", false, "", "Plex"),
                    ("Miscellaneous", "Bellydance Core Conditioning", "2005", "Neena & Veena", "NR", false, "", "Plex"),
                    ("Comedy", "Best In Show", "2000", "Christopher Guest", "PG-13", false, "", "Plex"),
                    ("Family", "Best Two Years, The", "2003", "Scott S. Anderson", "PG", false, "", "Plex"),
                    ("Comedy", "Better Off Dead", "1985", "Savage Steve Holland", "PG", false, "", "Plex"),
                    ("Comedy", "Big", "1988", "Penny Marshall", "PG", false, "", "Plex"),
                    ("Drama", "Big Fish", "2003", "Tim Burton", "PG-13", false, "", "Plex"),
                    ("Comedy", "Bill & Ted's Bogus Journey", "1991", "Peter Hewitt", "PG", false, "", "Plex"),
                    ("Comedy", "Bill & Ted's Excellent Adventure", "1989", "Stephen Herek", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Blackmail", "1929", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Horror/Suspense", "Blair Witch Project, The", "1999", "Eduardo Sánchez, Daniel Myrick", "R", true, "", "Plex"),
                    ("Miscellaneous", "Blue Man Group - The Complex Rock Tour Live", "2003", "Matt Goldman, Phil Stanton, Chris Wink", "NR", false, "", "Plex"),
                    ("Action/Adventure", "Boondock Saints, The", "1999", "Troy Duffy", "R", true, "", "Plex"),
                    ("Drama", "Braveheart", "1995", "Mel Gibson", "R", true, "", "Plex"),
                    ("Comedy", "Brian Regan: I Walked on the Moon", "2004", "John Brenkus", "NR", false, "", "Plex"),
                    ("Horror/Suspense", "Bride of Frankenstein, The", "1935", "James Whale", "NR", false, "", "Plex"),
                    ("Comedy", "Bridesmaids", "2011", "Paul Feig", "R", true, "", "Plex"),
                    ("Comedy", "Bruce Almighty", "2003", "Tom Shadyac", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Buffy the Vampire Slayer", "1992", "Fran Rubel Kuzui", "PG-13", false, "", "Plex"),
                    ("Comedy", "Buster Keaton Collection", "1920", "Buster Keaton", "UR", false, "", ""),
                    ("Horror/Suspense", "Cabin in the Woods", "2012", "Drew Goddard", "R", true, "", "Plex"),
                    ("Family", "Cars", "2006", "John Lasseter", "G", false, "", "Plex"),
                    ("Miscellaneous", "Cartoon Lagoon", "2012", "Euralis Weekes", "NR", false, "", ""),
                    ("Drama", "Casablanca", "1942", "Michael Curtiz", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Changeling, The", "1980", "Peter Medak", "PG", false, "", "Plex"),
                    ("Family", "Charlie and the Chocolate Factory", "2005", "Tim Burton", "PG", false, "", "Plex"),
                    ("Family", "Cheaper By The Dozen", "2003", "Shawn Levy", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Chronicle", "2012", "Josh Trank", "PG-13", false, "", "Plex"),
                    ("Family", "Cinderella", "1950", "Clyde Geronimi, Wilfred Jackson, Hamilton Luske", "G", false, "", "Plex"),
                    ("Family", "Cinderella", "2015", "Kenneth Branagh", "PG", false, "", "Plex"),
                    ("Family", "Cinderella Story, A", "2004", "Mark Rosman", "PG", false, "", "Plex"),
                    ("Family", "Cloudy with a Chance of Meatballs", "2009", "Chris Miller, Phil Lord", "G", false, "", "Plex"),
                    ("Comedy", "Clue", "1985", "Jonathan Lynn", "PG", false, "", "Plex"),
                    ("Comedy", "Cocoanuts, The", "1929", "Joseph Santley, Robert Florey", "G", false, "", "Blu-ray"),
                    ("Television", "Community (Season 1)", "2009 - 2010", "Dan Harmon", "TV-PG", false, "", "Plex"),
                    ("Television", "Community (Season 2)", "2010 - 2011", "Dan Harmon", "TV-PG", false, "", "Plex"),
                    ("Television", "Community (Season 3)", "2011-2012", "Dan Harmon", "TV-PG", false, "", "Plex"),
                    ("Television", "Community (Season 4)", "2013", "Dan Harmon", "TV-PG", false, "", "Plex"),
                    ("Television", "Community (Season 5)", "2014", "Dan Harmon", "TV-PG", false, "", "Plex"),
                    ("Television", "Community (Season 6)", "2015", "Dan Harmon", "TV-PG", false, "", "Plex"),
                    ("Miscellaneous", "Core Secrets: 25 Minute Full Body Workout / Accelerated Core Training", "2003", "Gunnar Peterson", "NR", false, "", ""),
                    ("Drama", "Count of Monte Cristo, The", "2002", "Kevin Reynolds", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Creature from the Black Lagoon", "1954", "Jack Arnold", "NR", false, "", "Plex"),
                    ("Miscellaneous", "Crunch - Pick Your Spot Pilates", "2002", "Ellen Barrett", "NR", false, "", ""),
                    ("Action/Adventure", "Dark Knight Rises, The", "2012", "Christopher Nolan", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Dark Knight, The", "2008", "Christopher Nolan", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Dawn of the Dead", "2004", "Zack Snyder", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Dementia 13", "1963", "Francis Ford Coppola", "UR", false, "", "Plex"),
                    ("Drama", "Departed, The", "2006", "Martin Scorsese", "R", true, "", "Plex"),
                    ("Family", "Despicable Me", "2010", "Pierre Coffin, Chris Renaud", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Devil", "2010", "John Erick Dowdle", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Die Hard", "1988", "John McTiernan", "R", true, "", "Plex"),
                    ("Action/Adventure", "District 9", "2009", "Neill Blomkamp", "R", true, "", "Plex"),
                    ("Comedy", "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", "1964", "Stanley Kubrick", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Dracula", "1931", "Tod Browning, Karl Freund", "NR", false, "", "Plex"),
                    ("Comedy", "Dream Team, The", "1989", "Howard Zieff", "PG-13", false, "", "Plex"),
                    ("Comedy", "Duck Soup", "1933", "Leo McCarey", "G", false, "", "Blu-ray"),
                    ("Comedy", "Dumb & Dumber", "1994", "The Farrelly Brothers", "PG-13", false, "", "Plex"),
                    ("Family", "Emperor's New Groove, The", "2000", "Mark Dindal", "G", false, "", ""),
                    ("Family", "Enchanted", "2007", "Kevin Lima", "PG", false, "", "Plex"),
                    ("Family", "Ernest Goes to Camp", "1987", "John R. Cherry III", "PG", false, "", "Plex"),
                    ("Family", "Ernest Goes to Jail", "1990", "John R. Cherry III", "PG", false, "", "Plex"),
                    ("Family", "Ernest Scared Stupid", "1991", "John R. Cherry III", "PG", false, "", "Plex"),
                    ("Drama", "Eternal Sunshine of the Spotless Mind", "2004", "Michel Gondry", "R", true, "", "Plex"),
                    ("Drama", "Far and Away", "1992", "Ron Howard", "PG-13", false, "", "Plex"),
                    ("Miscellaneous", "Faux Paw Adventures in the Internet", "2008", "Kreg Peeler", "NR", false, "", "Plex"),
                    ("Comedy", "Ferris Bueller's Day Off", "1986", "John Hughes", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Fido", "2006", "Andrew Currie", "R", false, "", "Plex"),
                    ("Family", "Finding Nemo", "2003", "Andrew Stanton", "G", false, "", ""),
                    ("Drama", "Finding Neverland", "2004", "Marc Forster", "PG", false, "", "Plex"),
                    ("Television", "Firefly: The Complete Series", "2002-2003", "Joss Whedon", "TV-14", false, "", "Plex"),
                    ("Comedy", "Fletch", "1985", "Michael Ritchie", "PG", false, "", "Plex"),
                    ("Comedy", "Fletch Lives", "1989", "Michael Ritchie", "PG", false, "", "Plex"),
                    ("Family", "Flight of Dragons, The", "1982", "Arthur Rankin & Jules Bass", "NR", false, "", ""),
                    ("Horror/Suspense", "Frankenstein", "1931", "James Whale", "NR", false, "", "Plex"),
                    ("Horror/Suspense", "Frankenstein Meets the Wolf Man", "1943", "Roy William Neill", "UR", false, "", "Plex"),
                    ("Horror/Suspense", "Garfield's Halloween Adventure", "1985", "Phil Roman", "TV-G", false, "", "Amazon Prime"),
                    ("Comedy", "General, The", "1927", "Buster Keaton", "UR", false, "", "Plex"),
                    ("Comedy", "Ghostbusters", "1984", "Ivan Reitman", "PG", false, "", "Plex"),
                    ("Drama", "Gone with the Wind", "1939", "Victor Fleming", "G", false, "", "Plex"),
                    ("Family", "Goofy Movie, A", "1995", "Kevin Lima", "G", false, "", "Plex"),
                    ("Family", "Goonies, The", "1985", "Richard Donner", "PG", false, "", "Plex"),
                    ("Family", "Great Muppet Caper, The", "1981", "Jim Henson", "G", false, "", "Plex"),
                    ("Family", "Greatest Showman, The", "2017", "Michael Gracey", "PG", false, "", "Plex"),
                    ("Drama", "Green Mile, The", "1999", "Frank Darabont", "R", true, "", "Plex"),
                    ("Comedy", "Gremlins", "1984", "Joe Dante", "PG", false, "", "Plex"),
                    ("Comedy", "Gremlins 2: The New Batch", "1990", "Joe Dante", "PG-13", false, "", "Plex"),
                    ("Comedy", "Groundhog Day", "1993", "Harold Ramis", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Grudge, The", "2004", "Takashi Shimizu", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Harry Potter and the Chamber of Secrets", "2002", "Chris Columbus", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Harry Potter and the Deathly Hallows – Part 1", "2010", "David Yates", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Harry Potter and the Deathly Hallows – Part 2", "2011", "David Yates", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Harry Potter and the Goblet of Fire", "2005", "Mike Newell", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Harry Potter and the Half-Blood Prince", "2009", "David Yates", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Harry Potter and the Order of the Phoenix", "2007", "David Yates", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Harry Potter and the Prisoner of Azkaban", "2004", "Alfonso Cuarón", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Harry Potter and the Sorcerer's Stone", "2001", "Chris Columbus", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Haunted Honeymoon", "1986", "Gene Wilder", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Haunting, The", "1963", "Robert Wise", "NR", false, "", "Plex/Amazon Prime"),
                    ("Drama", "He Loves Me... He Loves Me Not", "2002", "Laetitia Colombani", "PG-13", false, "", "Plex"),
                    ("Comedy", "Heart and Souls", "1993", "Ron Underwood", "PG-13", false, "", "Plex"),
                    ("Family", "Heidi's Song", "1982", "Robert Taylor", "G", false, "", ""),
                    ("Family", "High School Musical", "2006", "Kenny Ortega", "G", false, "", "Plex"),
                    ("Comedy", "Hitch", "2005", "Andy Tennant", "PG-13", false, "", "Plex"),
                    ("Family", "Home Alone", "1990", "Chris Columbus", "PG", false, "", "Plex"),
                    ("Family", "Honey, I Shrunk the Kids", "1989", "Joe Johnston", "PG", false, "", "Plex"),
                    ("Family", "Hook", "1991", "Steven Spielberg", "PG", false, "", "Plex"),
                    ("Comedy", "Horse Feathers", "1932", "Norman Z. McLeod", "G", false, "", "Blu-ray"),
                    ("Comedy", "Hot Fuzz", "2007", "Edgar Wright", "R", true, "", "Plex"),
                    ("Comedy", "Hot Shots!", "1991", "Jim Abrahams", "PG-13", false, "", "Plex"),
                    ("Comedy", "Hot Shots! Part Deux", "1993", "Jim Abrahams", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "House on Haunted Hill", "1959", "William Castle", "NR", false, "", "Rifftrax"),
                    ("Family", "How to Succeed in Business Without Really Trying", "1967", "David Swift", "UR", false, "", "Plex"),
                    ("Comedy", "Hudsucker Proxy, The", "1994", "Joel Coen, Ethan Coen", "PG", false, "", "Plex"),
                    ("Comedy", "I Love You, Man", "2009", "John Hamburg", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Identity", "2003", "James Mangold", "R", true, "", "Plex"),
                    ("Family", "In the Good Old Summertime", "1949", "Buster Keaton, Robert Z. Leonard", "UR", false, "", "Plex"),
                    ("Action/Adventure", "Inception", "2010", "Christopher Nolan", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Incredible Hulk, The", "2008", "Louis Leterrier", "PG-13", false, "", "Plex"),
                    ("Family", "Incredibles, The", "2004", "Brad Bird", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Independence Day", "1996", "Roland Emmerich", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Indiana Jones and the Last Crusade", "1989", "Steven Spielberg", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Indiana Jones and the Raiders of the Lost Ark", "1981", "Steven Spielberg", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Indiana Jones and the Temple of Doom", "1984", "Steven Spielberg", "PG", false, "", "Plex"),
                    ("Comedy", "Innerspace", "1987", "Joe Dante", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Invaders From Mars", "1986", "Tobe Hooper", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Invisible Man, The", "1933", "James Whale", "NR", false, "", "Plex"),
                    ("Action/Adventure", "Iron Man", "2008", "Jon Favreau", "PG-13", false, "", "Plex"),
                    ("Family", "It's a Wonderful Life", "1946", "Frank Capra", "NR", false, "", "Plex"),
                    ("Action/Adventure", "Italian Job, The", "2003", "F. Gary Gray", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Jaws", "1975", "Steven Spielberg", "PG", false, "", "Plex"),
                    ("Comedy", "Josie and the Pussycats", "2001", "Harry Elfont, Deborah Kaplan", "PG-13", false, "", "Plex"),
                    ("VHS", "Joy Ride", "2001", "John Dahl", "R", true, "", ""),
                    ("Family", "Jumanji", "1995", "Joe Johnston", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Juno & The Paycock", "1930", "Alfred Hitchcock", "UR", false, "", ""),
                    ("Action/Adventure", "Jurassic Park", "1993", "Steven Spielberg", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Kick-@$$", "2010", "Matthew Vaughn", "R", true, "", "Plex"),
                    ("Comedy", "Kid, The", "1921", "Charlie Chaplin", "UR", false, "", "Plex"),
                    ("Comedy", "King of Kong: A Fistful of Quarters, The", "2007", "Seth Gordon", "PG-13", false, "", "Plex"),
                    ("Comedy", "Kung Fu Hustle", "2005", "Stephen Chow", "R", true, "", "Plex"),
                    ("Comedy", "Kung Pow! Enter the Fist", "2001", "Steve Oedekerk", "PG-13", false, "", "Plex"),
                    ("Drama", "La La Land", "2016", "Damien Chazelle", "PG-13", false, "", "Plex"),
                    ("Family", "Labyrinth", "1986", "Jim Henson", "PG", false, "", "Plex"),
                    ("Drama", "Ladder 49", "2004", "Jay Russell", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Lady in White", "1988", "Frank Laloggia", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Lady Vanishes, The", "1938", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Action/Adventure", "Ladyhawke", "1985", "Richard Donner", "PG-13", false, "", "Plex"),
                    ("Drama", "Lars and the Real Girl", "2007", "Craig Gillespie", "PG-13", false, "", "Plex"),
                    ("Family", "Leap Frog: Letter Factory", "2009", "Roy Allen Smith", "G", false, "", "Plex"),
                    ("Family", "Leap!", "2016", "Eric Summer, Éric Warin", "PG", false, "", "YouTube Movies"),
                    ("Drama", "Leave Her to Heaven", "1945", "John M. Stahl", "UR", false, "", "Plex"),
                    ("Family", "Lego Movie, The", "2014", "Chris Miller, Phil Lord", "PG", false, "", "Plex"),
                    ("Drama", "Les Misérables", "1998", "Billie August", "PG-13", false, "", "Plex"),
                    ("Miscellaneous", "Les Miserables the Musical That Swept the World in Concert: The Dream Cast", "1995", "Gavin Taylor, Paul Kafno", "NR", false, "", "Plex"),
                    ("Family", "Lion King, The", "1994", "Rob Minkoff, Roger Allers", "G", false, "", "Plex"),
                    ("Family", "Little Mermaid, The", "1989", "Ron Clements, John Musker", "G", false, "", "Plex"),
                    ("Drama", "Little Miss Sunshine", "2006", "Jonathan Dayton, Valerie Faris", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Little Shop of Horrors", "1986", "Frank Oz", "PG-13", false, "", "Blu-ray"),
                    ("Action/Adventure", "Live Die Repeat: Edge of Tomorrow", "2014", "Doug Liman", "PG-13", false, "", "Plex"),
                    ("Family", "Lizzie McGuire Movie, The", "2003", "Jim Fall", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Lock, Stock and Two Smoking Barrels", "1999", "Guy Ritchie", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Lodger", "1927", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Action/Adventure", "Lord of the Rings: The Fellowship of the Ring", "2001", "Peter Jackson", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Lord of the Rings: The Return of the King, The", "2003", "Peter Jackson", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Lord of the Rings: The Two Towers, The", "2002", "Peter Jackson", "PG-13", false, "", "Plex"),
                    ("Comedy", "Love Actually", "2003", "Richard Curtis", "R", true, "", "Plex"),
                    ("Action/Adventure", "Lucky Number Slevin", "2006", "Paul McGuigan", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Mad Monster Party", "1999", "Jules Bass", "NR", false, "", "Amazon Prime"),
                    ("Television", "Malcolm in the Middle (Season 1)", "2000", "Linwood Boomer", "TV-PG", false, "", "Plex"),
                    ("Horror/Suspense", "Man Who Knew Too Much, The", "1934", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Family", "Marley & Me", "2008", "David Frankel", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Mask of Zorro, The", "1998", "Martin Campbell", "PG-13", false, "", "Plex"),
                    ("Comedy", "Mask, The", "1994", "Chuck Russell", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Masque of the Red Death, The", "1964", "Roger Corman", "UR", false, "", "Plex"),
                    ("Comedy", "Matador, The", "2005", "Richard Shepard", "R", true, "", "Plex"),
                    ("Family", "Matilda", "1996", "Danny DeVito", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Matrix, The", "1999", "The Wachowski Brothers", "R", false, "", "Plex"),
                    ("Comedy", "Maverick", "1994", "Richard Donner", "PG", false, "", "Plex"),
                    ("Drama", "Memento", "2001", "Christopher Nolan", "R", true, "", "Plex"),
                    ("Comedy", "Men in Black", "1997", "Barry Sonnenfeld", "PG-13", false, "", "Plex"),
                    ("Drama", "Metropolis", "1927", "Fritz Lang", "UR", false, "", "Blu-ray"),
                    ("Comedy", "Mighty Wind, A", "2003", "Christopher Guest", "PG-13", false, "", "Plex"),
                    ("Drama", "Millions", "2004", "Danny Boyle", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Mission: Impossible", "1996", "Brian De Palma", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Mission: Impossible II", "2000", "John Woo", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Mission: Impossible III", "2006", "J.J. Abrams ", "PG-13", false, "", "Plex"),
                    ("Family", "Moana", "2016", "Ron Clements, John Musker", "PG", false, "", "Plex"),
                    ("Comedy", "Monkey Business", "1931", "Norman Z. McLeod", "G", false, "", "Blu-ray"),
                    ("Family", "Monster House", "2006", "Gil Kenan", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Monster Squad, The", "1987", "Fred Dekker", "PG-13", false, "", "Plex"),
                    ("Family", "Monsters, Inc.", "2001", "Pete Docter, Lee Unkrich, David Silverman", "G", false, "", "Plex"),
                    ("Comedy", "Monty Python and the Holy Grail", "1975", "Terry Gilliam, Terry Jones", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Mothman Prophecies, The", "2002", "Mark Pellington", "PG-13", false, "", "Plex"),
                    ("Drama", "Moulin Rouge!", "2001", "Baz Luhrmann", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Mr. & Mrs. Smith", "2005", "Doug Liman", "PG-13", false, "", "Plex"),
                    ("Family", "Mr. Krueger's Christmas", "1980", "Kieth Merrill", "NR", false, "", "Plex"),
                    ("Family", "Mr. Popper's Penguins", "2011", "Mark Waters", "PG", false, "", "Plex"),
                    ("Comedy", "Mrs. Doubtfire", "1993", "Chris Columbus", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Mummy, The", "1932", "Karl Freund", "NR", false, "", "Plex"),
                    ("Family", "Muppet Movie, The", "1979", "James Frawley", "G", false, "", "Plex"),
                    ("Family", "Muppets, The", "2011", "James Bobin", "PG", false, "", "Plex"),
                    ("Comedy", "My Big Fat Greek Wedding", "2002", "Joel Zwick", "PG", false, "", "Plex"),
                    ("Family", "My Little Pony: Equestria Girls", "2013", "Jayson Thiessen", "G", false, "", "Plex"),
                    ("Comedy", "Mystery Men", "1999", "Kinka Usher", "PG-13", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000 Collection, Volume 1, The", "2002", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000 Collection, Volume 2, The", "2003", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000 Collection, Volume 4, The", "2003", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000 Collection, Volume 5, The", "2004", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000 Collection, Volume 8, The", "2005", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000: 20th Anniversary Edition", "2008", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000: Eegah!", "1993", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000: Escape 2000", "1996", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000: Mitchell", "1993", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000: Samson vs. Vampire Women", "1995", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000: The Essentials", "2004", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Comedy", "Mystery Science Theater 3000: The Movie", "1996", "Jim Mallon", "PG-13", false, "", "Plex"),
                    ("Television", "Mystery Science Theater 3000: Wild World of Batwoman", "1993", "Joel Hodgson", "TV-14", false, "", "Plex"),
                    ("Comedy", "Naked Gun 2½: The Smell of Fear, The", "1991", "David Zucker", "PG-13", false, "", "Plex"),
                    ("Comedy", "Naked Gun: From the Files of Police Squad!, The", "1988", "David Zucker", "PG-13", false, "", "Plex"),
                    ("Comedy", "Napoleon Dynamite", "2004", "Jared Hess", "PG", false, "", "Plex"),
                    ("Comedy", "National Lampoon's Loaded Weapon 1", "1993", "Gene Quintano", "PG-13", false, "", "Plex"),
                    ("Family", "NeverEnding Story, The", "1984", "Wolfgang Petersen", "PG", false, "", "Plex"),
                    ("Family", "Newsies", "1992", "Kenny Ortega", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Night of the Living Dead", "1968", "George A. Romero", "UR", false, "", "Plex"),
                    ("Family", "Nightmare Before Christmas, The", "1993", "Henry Selick", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Nosferatu", "1922", "F. W. Murnau", "UR", false, "", "Plex"),
                    ("Action/Adventure", "Ocean's Eleven", "2001", "Steven Soderbergh", "PG-13", false, "", "Plex"),
                    ("Miscellaneous", "Ogden: Junction City of the West", "2007", "Issac Goeckeritz", "NR", false, "", ""),
                    ("Family", "One Magic Christmas", "1985", "Phillip Borsos", "G", false, "", "Plex"),
                    ("Family", "Open Season", "2006", "Anthony Stacchi, Roger Allers, Jill Culton", "G", false, "", "Plex"),
                    ("Comedy", "Opportunity Knocks", "1990", "Donald Petrie", "PG-13", false, "", "Plex"),
                    ("Comedy", "Oscar", "1991", "John Landis", "PG", false, "", "Plex"),
                    ("Miscellaneous", "Pet Shop", "2005", "Trent Halvorsen", "NR", false, "", "Plex"),
                    ("Family", "Peter Pan", "1953", "Hamilton Luske, Clyde Geronimi, Wilfred Jackson", "G", false, "", "Plex"),
                    ("Drama", "Phantom of the Opera, The", "2005", "Joel Schumacher", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Phantom of the Opera, The", "1925", "Lon Chaney, Sr., Edward Sedgwick, Rupert Julian, Ernst Laemmle", "UR", false, "", "Plex"),
                    ("Action/Adventure", "Phone Booth", "2003", "Joel Schumacher", "R", true, "", "Plex"),
                    ("Family", "Pink Panther and Friends Classic Cartoon Collection, Vol. 5: The Ant and the Aardvark, The", "2007", "Robert Sledge", "G", false, "", ""),
                    ("Action/Adventure", "Pirates of the Caribbean: The Curse of the Black Pearl", "2003", "Gore Verbinski", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Plan 9 from Outer Space", "1959", "Ed Wood", "UR", false, "", "Plex"),
                    ("Comedy", "Planes, Trains and Automobiles", "1987", "John Hughes", "R", true, "", "Plex"),
                    ("Television", "Police Squad! The Complete Series", "1982", "Jim Abrahams, David Zucker, Jerry Zucker", "TV-PG", false, "", "Plex"),
                    ("Family", "Pollyanna", "1960", "David Swift", "G", false, "", "Plex"),
                    ("Drama", "Power of One, The", "1992", "John G. Avildsen", "PG-13", false, "", "Plex"),
                    ("Family", "Praise to the Man", "2005", "T.C. Christensen, Gary Cook", "NR", false, "", "Plex"),
                    ("Action/Adventure", "Predator", "1987", "John McTiernan", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Premature Burial, The", "1962", "Roger Corman", "UR", false, "", "Plex"),
                    ("Drama", "Pride and Prejudice", "2005", "Joe Wright", "PG", false, "", "Plex"),
                    ("Family", "Princess Bride, The", "1986", "Rob Reiner", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Psycho", "1960", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Television", "Pushing Daisies (Season 1)", "2007", "Bryan Fuller", "TV-PG", false, "", "Plex"),
                    ("Television", "Pushing Daisies (Season 2)", "2008-2009", "Bryan Fuller", "TV-PG", false, "", "Plex"),
                    ("Comedy", "Pyromaniac's Love Story, A", "1995", "Joshua Brand", "PG", false, "", "Plex"),
                    ("Comedy", "Raising Arizona", "1987", "Joel Coen, Ethan Coen", "PG-13", false, "", "Plex"),
                    ("Family", "Ratatouille", "2007", "Brad Bird, Jan Pinkava", "G", false, "", "Plex"),
                    ("Horror/Suspense", "Rear Window", "1954", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Horror/Suspense", "Return of Dracula, The", "1958", "Paul Landres", "UR", false, "", "Plex"),
                    ("Horror/Suspense", "Rich & Strange", "1931", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Horror/Suspense", "Ring, The", "1927", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Horror/Suspense", "Ring, The", "2002", "Gore Verbinski", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Robin Hood: Prince of Thieves", "1991", "Kevin Reynolds", "PG-13", false, "", "Amazon Prime"),
                    ("Action/Adventure", "Rocketeer, The", "1991", "Joe Johnston", "PG", false, "", "Plex"),
                    ("Television", "Roswell (Season 1)", "1999-2000", "Jonathon Dukes", "TV-14", false, "", "Plex"),
                    ("Television", "Roswell (Season 2)", "2000-2001", "Jonathon Dukes", "TV-14", false, "", "Plex"),
                    ("Television", "Roswell (Season 3)", "2001-2002", "Jonathon Dukes", "TV-14", false, "", "Plex"),
                    ("Comedy", "Royal Tenenbaums, The", "2001", "Wes Anderson", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Sabotage", "1936", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Family", "Sandlot, The", "1993", "David M. Evans", "PG", false, "", "Plex"),
                    ("Television", "Saturday Night Live - 25th Anniversary", "2004", "Lorne Michaels", "TV-14", false, "", "Plex"),
                    ("Family", "Saturday's Warrior", "1989", "Bob Williams", "G", false, "", "Plex"),
                    ("Television", "Saved By the Bell (Season 5)", "1992-1993", "Sam Bobrick", "TV-PG", false, "", "Plex"),
                    ("Television", "Saved by the Bell (Seasons 1 & 2)", "1989-1990", "Sam Bobrick", "TV-PG", false, "", "Plex"),
                    ("Television", "Saved by the Bell (Seasons 3 & 4) ", "1990-1992", "Sam Bobrick", "TV-PG", false, "", "Plex"),
                    ("Television", "Saved by the Bell: Hawaiian Style", "1992", "Don Barnhart", "TV-PG", false, "", "Amazon Prime"),
                    ("Television", "Saved by the Bell: The College Years", "1993-1994", "Miguel Higuera, Jeffrey Melman", "TV-PG", false, "", "Amazon Prime"),
                    ("Television", "Saved by the Bell: Wedding in Las Vegas", "1994", "Don Barnhart, Jeffrey Melman", "TV-PG", false, "", "Amazon Prime"),
                    ("Horror/Suspense", "Saw", "2004", "James Wan", "R", true, "", "Plex"),
                    ("Comedy", "Say Anything", "1989", "Cameron Crowe", "PG-13", false, "", "Plex"),
                    ("Comedy", "School of Rock", "2003", "Richard Linklater", "PG-13", false, "", "Plex"),
                    ("Television", "Scooby-Doo! Dynomutt Hour, The", "1976", "Charles A. Nichols", "TV-Y7", false, "", "Plex"),
                    ("Horror/Suspense", "Secret Agent", "1936", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Comedy", "Serendipity", "2001", "Peter Chelsom", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Serenity", "2005", "Joss Whedon", "PG-13", false, "", "Plex"),
                    ("Miscellaneous", "Seven Days Seven Workouts", "2005", "N/A", "NR", false, "", ""),
                    ("Horror/Suspense", "Shaun of the Dead", "2004", "Edgar Wright", "R", true, "", "Plex"),
                    ("Drama", "Shawshank Redemption, The", "1994", "Frank Darabont", "R", true, "", "Plex"),
                    ("Horror/Suspense", "She-Wolf of London", "1946", "Jean Yarbrough", "UR", false, "", "Plex"),
                    ("Family", "Shop Around the Corner, The", "1940", "Ernst Lubitsch", "UR", false, "", "Plex"),
                    ("Family", "Shrek", "2001", "Andrew Adamson, Vicky Jenson", "PG", false, "", "Plex"),
                    ("Family", "Shrek 2", "2004", "Andrew Adamson, Kelly Asbury, Conrad Vernon", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "Signs", "2002", "M. Night Shyamalan", "PG-13", false, "", "Plex"),
                    ("Drama", "Silver Linings Playbook", "2012", "David O. Russell", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Sixth Sense, The", "1999", "M. Night Shyamalan", "PG-13", false, "", "Plex"),
                    ("Family", "Sleeping Beauty", "1959", "Clyde Geronimi", "G", false, "", "Plex"),
                    ("Drama", "Sliding Doors", "1998", "Peter Howitt", "PG-13", false, "", "Plex"),
                    ("Drama", "Slumdog Millionaire", "2008", "Danny Boyle", "R", false, "", "Plex"),
                    ("Action/Adventure", "Snatch", "2001", "Guy Ritchie", "R", true, "", "Plex"),
                    ("Action/Adventure", "Sneakers", "1992", "Phil Alden Robinson", "PG-13", false, "", "Plex"),
                    ("Family", "Snow White and the Seven Dwarfs", "1938", "Larry Morey, Wilfred Jackson, Ben Sharpsteen, Perce Pearce, David Hand, William Cottrell", "G", false, "", "Plex"),
                    ("Comedy", "So I Married An Axe Murderer", "1993", "Thomas Schlamme", "PG-13", false, "", "Plex"),
                    ("Family", "Song of the South", "1946", "Harve Foster, Wilfred Jackson", "G", false, "", "Plex"),
                    ("Family", "Sound of Music, The", "1965", "Robert Wise", "G", false, "", "Plex"),
                    ("Action/Adventure", "Spider-Man", "2002", "Sam Raimi", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Spider-Man 2", "2004", "Sam Raimi", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Spider-Man: Into the Spider-Verse", "2018", "Peter Ramsey, Bob Persichetti, Rodney Rothman", "PG", false, "", "Plex"),
                    ("Comedy", "Spies Like Us", "1985", "John Landis", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Star Wars Episode I: The Phantom Menace", "1999", "George Lucas", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Star Wars Episode II: Attack of the Clones", "2002", "George Lucas", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Star Wars Episode III: Revenge of the Sith", "2005", "George Lucas", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Star Wars Episode IV: A New Hope", "1977", "George Lucas", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Star Wars Episode V: The Empire Strikes Back", "1980", " Irvin Kershner", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Star Wars Episode VI: Return of the Jedi", "1983", "Richard Marquand", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Stargate", "1994", "Roland Emmerich", "PG-13", false, "", "YouTube Movies"),
                    ("Comedy", "Steamboat Bill, Jr.", "1928", "Buster Keaton", "G", false, "", "Plex"),
                    ("Horror/Suspense", "Strange Invaders", "1983", "Michael Laughlin", "PG", false, "", "Plex"),
                    ("Drama", "Stranger than Fiction", "2006", "Marc Forster", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "Superman II", "1980", "Richard Lester", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Superman III", "1983", "Richard Lester", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Superman IV: The Quest for Peace", "1987", "Sidney J. Furie", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Superman: The Movie", "1978", "Richard Donner", "PG", false, "", "Plex"),
                    ("Comedy", "Supersize Me", "2004", "Morgan Spurlock", "PG-13", false, "", "Plex"),
                    ("Family", "Support Your Local Gunfighter", "1971", "Burt Kennedy", "G", false, "", "Plex"),
                    ("Family", "Support Your Local Sheriff", "1969", "Burt Kennedy", "G", false, "", "Plex"),
                    ("Horror/Suspense", "Sweeney Todd: The Demon Barber of Fleet Street", "2007", "Tim Burton", "R", true, "", "Plex"),
                    ("Comedy", "Sweet Home Alabama", "2002", "Andy Tennant", "PG-13", false, "", "Plex"),
                    ("Family", "Sword in the Stone, The", "1963", "Wolfgang Reitherman", "G", false, "", "Plex"),
                    ("Comedy", "Team America: World Police", "2004", "Trey Parker", "R", true, "", "Plex"),
                    ("Family", "Teenage Mutant Ninja Turtles", "1990", "Steve Barron", "PG", false, "", "Plex"),
                    ("Family", "Teenage Mutant Ninja Turtles II: The Secret of the Ooze", "1991", "Michael Pressman", "PG", false, "", "Plex"),
                    ("Action/Adventure", "Terminator 2: Judgment Day", "1991", "James Cameron", "R", true, "", "Plex"),
                    ("Action/Adventure", "The Fugitive", "1993", "Andrew Davis", "PG-13", false, "", "Plex"),
                    ("Family", "They Might Be Giants: Here Comes Science", "2009", "John Linnell, John Flansburgh", "G", false, "", ""),
                    ("Family", "They Might Be Giants: Here Comes the 123s", "2008", "John Linnell, John Flansburgh", "G", false, "", "Plex"),
                    ("Family", "They Might Be Giants: Here Comes the ABCs", "2005", "John Linnell, John Flansburgh", "G", false, "", "Plex"),
                    ("Horror/Suspense", "Thing from Another World, The", "1951", "Christian Nyby, Howard Hawks", "UR", false, "", "Plex"),
                    ("Comedy", "Three Amigos", "1986", "John Landis", "PG", false, "", "Plex"),
                    ("Comedy", "Tillie's Punctured Romance", "1914", "Mack Sennett", "UR", false, "", "Plex"),
                    ("Comedy", "Tommy Boy", "1995", "Peter Segal", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Tormented", "1960", "Bert I. Gordon", "UR", false, "", "Plex"),
                    ("Family", "Toy Story", "1995", "John Lasseter", "G", false, "", "Plex"),
                    ("Family", "Toy Story 2", "1999", "John Lasseter", "G", false, "", "Plex"),
                    ("Family", "Toy Story 3", "2010", "Lee Unkrich", "G", false, "", "Plex"),
                    ("Drama", "True Grit", "2010", "Joel Coen, Ethan Coen", "PG-13", false, "", "Plex"),
                    ("Drama", "Truman Show, The", "1998", "Peter Weir", "PG", false, "", "Plex"),
                    ("Comedy", "UHF", "1989", "Jay Levey", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Unbreakable", "2000", "M. Night Shyamalan", "PG-13", false, "", "Plex"),
                    ("Drama", "Unforgiven", "1992", "Clint Eastwood", "R", true, "", "Plex"),
                    ("VHS", "Untouchables", "1987", "Brian De Palma", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Vacancy", "2007", "Nimród Antal", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Vampire, The", "1957", "Paul Landres", "UR", false, "", "Plex"),
                    ("Horror/Suspense", "Village, The", "2004", "M. Night Shyamalan", "PG-13", false, "", "Plex"),
                    ("Comedy", "Waiting For Guffman", "1996", "Christopher Guest", "R", true, "", "Plex"),
                    ("Comedy", "Waking Ned Devine", "1998", "Kirk Jones", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "War of the Worlds, The", "1953", "Byron Haskin", "G", false, "", ""),
                    ("Action/Adventure", "Watchmen", "2009", "Zack Snyder", "R", true, "", "Plex"),
                    ("Comedy", "Wayne's World", "1992", "Penelope Spheeris", "PG-13", false, "", "Plex"),
                    ("Family", "We Bought a Zoo", "2011", "Cameron Crowe", "PG", false, "", "Plex"),
                    ("Comedy", "Wedding Planner, The", "2001", "Adam Shankman", "PG-13", false, "", "Plex"),
                    ("Comedy", "Weekend at Bernie's", "1989", "Ted Kotchef", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Werewolf of London", "1935", "Stuart Armstrong Walker", "UR", false, "", "Plex"),
                    ("Family", "What a Girl Wants", "2003", "Dennie Gordon", "PG", false, "", "Plex"),
                    ("Horror/Suspense", "What's the Matter With Helen?", "1971", "Curtis Harrington", "R?", false, "", "Plex"),
                    ("Horror/Suspense", "Whoever Slew Auntie Roo?", "1972", "Curtis Harrington", "PG-13", false, "", "Plex"),
                    ("Family", "Willy Wonka and the Chocolate Factory", "1971", "Mel Stuart", "G", false, "", "Plex"),
                    ("Television", "Wings (Season 1 & 2)", "1990-1991", "David Angell, Peter Casey, David Lee", "TV-PG", false, "", "Plex"),
                    ("Television", "Wings (Season 3)", "1991-1992", "David Angell, Peter Casey, David Lee", "TV-PG", false, "", "Plex"),
                    ("Television", "Wings (Season 4)", "1992-1993", "David Angell, Peter Casey, David Lee", "TV-PG", false, "", "Plex"),
                    ("Television", "Wings (Season 5)", "1993-1994", "David Angell, Peter Casey, David Lee", "TV-PG", false, "", "Plex"),
                    ("Television", "Wings (Season 6)", "1994-1995", "David Angell, Peter Casey, David Lee", "TV-PG", false, "", "Plex"),
                    ("Television", "Wings (Season 7)", "1995-1996", "David Angell, Peter Casey, David Lee", "TV-PG", false, "", "Plex"),
                    ("Television", "Wings (Season 8)", "1996-1997", "David Angell, Peter Casey, David Lee", "TV-PG", false, "", "Plex"),
                    ("Horror/Suspense", "Wolf Man, The", "1941", "George Waggner", "UR", false, "", "Plex"),
                    ("Family", "Wonder", "2017", "Stephen Chbosky", "PG", false, "", "Plex"),
                    ("Family", "Wreck-It Ralph", "2012", "Rich Moore", "PG", false, "", "YouTube Movies"),
                    ("Action/Adventure", "X-Men", "2000", "Bryan Singer", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "X-Men: The Last Stand", "2006", "Brett Ratner ", "PG-13", false, "", "Plex"),
                    ("Action/Adventure", "X2", "2003", "Bryan Singer", "PG-13", false, "", "Plex"),
                    ("Horror/Suspense", "Young & Innocent", "1937", "Alfred Hitchcock", "UR", false, "", "Plex"),
                    ("Action/Adventure", "Young Guns", "1988", "Christopher Cain", "R", true, "", "Plex"),
                    ("Horror/Suspense", "Zombieland", "2009", "Ruben Fleischer", "R", true, "", "Plex"),
                    ("Family", "Zootopia", "2016", "Byron Howard, Rich Moore", "PG", false, "", "Plex")
                };

                foreach (var movie in movies)
                {
                    var directorId = GetOrCreateDirector(movie.Director);
                    var categoryId = categories[movie.Category];
                    var ratingId = ratings[movie.Rating];

                    context.Movies.Add(new Movie
                    {
                        Title = movie.Title,
                        Year = movie.Year,
                        DirectorId = directorId,
                        CategoryId = categoryId,
                        RatingId = ratingId,
                        Edited = movie.Edited,
                        LentTo = string.IsNullOrWhiteSpace(movie.LentTo) ? null : movie.LentTo,
                        Notes = string.IsNullOrWhiteSpace(movie.Notes) ? null : movie.Notes
                    });
                }

                context.SaveChanges();
            }
        }
    }
}
